### ISSUE TITLE
Editor enhancements (Kbd/List and SBS) gone

### ISSUE THREAD

**Issue by fixer1234** [soscripted/sox#186]
### Current Behaviour
The Kbd/List and SBS buttons have disappeared.  Checked on SU and Meta posts, Your Answer box, and Ask Question.  Unaffected by page refresh.

---

### SOX Errors logged to the browser console -- F12 (if available)
Since this applies to all edit windows, including Your Answer, I just loaded a random thread for the console output.

```
The connection to wss://qa.sockets.stackexchange.com/ was interrupted while the page was loading. full.en.js:1:6864
GET 
http://superuser.com/questions/735293/reclaiming-an-old-school-chromebook [HTTP/1.1 200 OK 64ms]
GET 
https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js [HTTP/2.0 304 Not Modified 16ms]
GET 
https://cdn.sstatic.net/Js/stub.en.js [HTTP/2.0 304 Not Modified 13ms]
GET 
https://cdn.sstatic.net/Sites/superuser/all.css [HTTP/2.0 304 Not Modified 13ms]
TypeError: can't access dead object jquery-2.1.4.min.js:2:30322
TypeError: can't access dead object jquery-2.1.4.min.js:2:30322
GET 
https://i.stack.imgur.com/DPd3M.jpg [HTTP/1.1 304 Not Modified 25ms]
GET 
http://static.adzerk.net/ados.js [HTTP/1.1 304 Not Modified 16ms]
GET 
https://www.google-analytics.com/analytics.js [HTTP/2.0 304 Not Modified 27ms]
GET 
http://edge.quantserve.com/quant.js [HTTP/1.1 304 Not Modified 41ms]
GET 
https://cdn.sstatic.net/img/share-sprite-new.svg [HTTP/2.0 304 Not Modified 14ms]
GET 
https://cdn.sstatic.net/Sites/superuser/img/sprites.svg [HTTP/2.0 304 Not Modified 27ms]
GET 
https://cdn.sstatic.net/img/favicons-sprite16.png [HTTP/2.0 304 Not Modified 13ms]
GET 
https://www.gravatar.com/avatar/b733b5cd384fa8006dcb20f6f298c290 [HTTP/2.0 304 Not Modified 16ms]
GET 
https://www.gravatar.com/avatar/9547e69a830ec5d8ee17c1a3c2a28bd5 [HTTP/2.0 304 Not Modified 13ms]
GET 
https://i.stack.imgur.com/bBmQb.png [HTTP/1.1 304 Not Modified 21ms]
GET 
http://b.scorecardresearch.com/beacon.js [HTTP/1.1 200 OK 14ms]
SOX:  undefined sox.common.js:16:13
SOX:  Object { init: StackExchange.init</<(n, s), debug: Object, initialized: Object, ready: StackExchange.ready(e), using: v(e, n, a, i), ifUsing: b(e, t, n), loadJsFile: StackExchange.loadJsFile(e, t), loadJqueryUi: StackExchange.loadJqueryUi(), helpers: Object, switchMobile: StackExchange.switchMobile(e), 5 more… } sox.common.js:16:13
SOX:  DEBUGGING SOX VERSION 2.0.3 DEV j sox.common.js:16:13
SOX:  ----------------saved variables--------------------- sox.common.js:16:13
SOX:  logging sox stored values ---  sox.common.js:40:13
SOX:  access token set sox.common.js:40:13
SOX:  SOX-debug sox.common.js:40:13
SOX:  true sox.common.js:40:13
SOX:  SOXSETTINGS sox.common.js:40:13
SOX:  ["Appearance-addAuthorNameToInboxNotifications","Appearance-alignBadgesByClass","Appearance-answerTagsSearch","Appearance-colorAnswerer","Appearance-fixedTopbar","Appearance-isQuestionHot","Appearance-markEmployees","Appearance-metaChatBlogStackExchangeButton","Appearance-metaNewQuestionAlert","Appearance-scrollToTop","Appearance-standOutDupeCloseMigrated","Appearance-tabularReviewerStats","Comments-autoShowCommentImages","Comments-commentReplies","Comments-commentShortcuts","Comments-confirmNavigateAway","Comments-showCommentScores","Comments-hiddenCommentsIndicator","Editing-addSBSBtn","Editing-editComment","Editing-editReasonTooltip","Editing-enhancedEditor","Editing-kbdAndBullets","Editing-titleEditDiff","Editing-inlineEditorEverywhere","Editing-downvotedPostsEditAlert","Flags-flagOutcomeTime","Flags-flagPercentages","Flags-flagPercentageBar","Sidebar-hideHireMe","Sidebar-linkedToFrom","Chat-chatEasyAccess","Chat-replyToOwnChatMessages","Chat-renameChat","Voting-grayOutVotes","Voting-disableOwnPostVoteButtons","Unsorted-alwaysShowImageUploadLinkBox","Unsorted-linkedPostsInline","Unsorted-parseCrossSiteLinks","Unsorted-quickAuthorInfo","Unsorted-shareLinksMarkdown","Unsorted-warnNotLoggedIn","Unsorted-showMetaReviewCount"] sox.common.js:40:13
SOX:  downvotedPostsEditAlert sox.common.js:40:13
SOX:  {"11990":{"questionId":"11990","addedDate":1482547897992,"sitename":"meta.superuser","lastCheckedTime":1482548962986}} sox.common.js:40:13
SOX:  downvotedPostsEditAlert-notifications sox.common.js:40:13
SOX:  {"11990":{"sitename":"meta","url":"http://meta.superuser.com/q/11990","title":"Show your Excel results","editor":"fixer1234","editor_link":"http://meta.superuser.com/users/364367/fixer1234","edit_date":1482548454,"type":"question"}} sox.common.js:40:13
SOX:  editReasons sox.common.js:40:13
SOX:  [["formatting","Improved Formatting"],["spelling","Corrected Spelling"],["grammar","Fixed grammar"],["greetings","Removed thanks/greetings"]] sox.common.js:40:13
SOX:  metaNewQuestionAlert-lastQuestions sox.common.js:40:13
SOX:  {"meta.superuser":"Show your Excel results"} sox.common.js:40:13
SOX:  ----------------end saved variables--------------------- sox.common.js:16:13
GET 
http://b.scorecardresearch.com/b [HTTP/1.1 204 No Content 20ms]
GET 
https://cdn.sstatic.net/Js/full.en.js [HTTP/2.0 304 Not Modified 14ms]
GET 
https://cdn.sstatic.net/Js/inline-tag-editing.en.js [HTTP/2.0 304 Not Modified 15ms]
XrayWrapper denied access to property "ready" (reason: value is callable). See https://developer.mozilla.org/en-US/docs/Xray_vision for more information. Note that only the first denied property access from a given global object will be reported. sox.common.js:72:0
GET 
https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css [HTTP/2.0 304 Not Modified 12ms]
SOX:  initializing SOX dialog sox.common.js:16:13
GET 
http://engine.adzerk.net/ados [HTTP/1.1 200 OK 139ms]
GET 
https://www.google-analytics.com/collect [HTTP/2.0 200 OK 16ms]
GET 
http://pixel.quantserve.com/pixel;r=1746233097;a=p-c1rF4kxgLUzNc;fpan=0;fpa=P0-2087723673-1465952398859;ns=0;ce=1;cm=;je=1;sr=2048x1152x24;enc=n;dst=1;et=1482549465557;tzo=300;ref=http%3A%2F%2Fsuperuser.com%2Fquestions;url=http%3A%2F%2Fsuperuser.com%2Fquestions%2F735293%2Freclaiming-an-old-school-chromebook;ogl=type.website%2Cimage.https%3A%2F%2Fcdn%252Esstatic%252Enet%2FSites%2Fsuperuser%2Fimg%2Fapple-touch-icon%402%252Epng%3Fv%3De869e445943%2Ctitle.Reclaiming%20an%20old%20school%20Chromebook%2Cdescription.In%20the%20middle%20school%20I%20go%20to%252C%20we%20use%20chromebooks%252E%20They%20are%20%22managed%22%252C%20so%20we%20cann%2Curl.http%3A%2F%2Fsuperuser%252Ecom%2Fquestions%2F735293%2Freclaiming-an-old-school-chromebook [HTTP/1.1 200 OK 41ms]
SOX:  injecting features into dialog sox.common.js:16:13
SOX:  Appearance sox.common.js:16:13
SOX:  addAuthorNameToInboxNotifications sox.common.js:16:13
SOX:  Object { name: "addAuthorNameToInboxNotifications", desc: "Add the author's name to notificati…", extended_description: "If you receive a comment/answer/sug…", meta: "", match: "", exclude: "" } sox.common.js:16:13
SOX:  running addAuthorNameToInboxNotifications sox.common.js:16:13
SOX:  observe: .inbox-dialog sox.common.js:16:13
SOX:  undefined sox.common.js:16:13
SOX:  Appearance sox.common.js:16:13
SOX:  alignBadgesByClass sox.common.js:16:13
SOX:  Object { name: "alignBadgesByClass", desc: "Align badges by their class on user…", meta: "http://meta.stackexchange.com/q/254…", match: "*://*/users/*", exclude: "SE1.0" } sox.common.js:16:13
SOX:  Appearance sox.common.js:16:13
SOX:  answerTagsSearch sox.common.js:16:13
SOX:  Object { name: "answerTagsSearch", desc: "Show tags for the question an answe…", meta: "http://meta.stackexchange.com/quest…", match: "*://*.com/search*", exclude: "SE1.0" } sox.common.js:16:13
SOX:  Appearance sox.common.js:16:13
SOX:  colorAnswerer sox.common.js:16:13
SOX:  Object { name: "colorAnswerer", desc: "Color answerer's comments", meta: "http://meta.stackexchange.com/quest…", match: "*://*/questions*", exclude: "SE1.0" } sox.common.js:16:13
SOX:  running colorAnswerer sox.common.js:16:13
SOX:  observe: .new_comment sox.common.js:16:13
SOX:  NodeList [ <table>, <table>, <table>, <table>, <table>, <table>, <table>, <table>, <table>, <table>, 1 more… ] sox.common.js:16:13
SOX:  Appearance sox.common.js:16:13
SOX:  fixedTopbar sox.common.js:16:13
SOX:  Object { name: "fixedTopbar", desc: "Fix topbar position", extended_description: "Locks the topbar to the top of the …", meta: "http://meta.stackexchange.com/quest…", match: "", exclude: "", settings: Array[1] } sox.common.js:16:13
SOX:  running fixedTopbar sox.common.js:16:13
SOX:  Appearance sox.common.js:16:13
SOX:  isQuestionHot sox.common.js:16:13
SOX:  Object { name: "isQuestionHot", desc: "Add a label on questions which are …", meta: "http://meta.stackexchange.com/quest…", match: "*://*/questions*", exclude: "SE1.0" } sox.common.js:16:13
SOX:  running isQuestionHot sox.common.js:16:13
SOX:  Appearance sox.common.js:16:13
SOX:  markEmployees sox.common.js:16:13
SOX:  Object { name: "markEmployees", desc: "Add the SO logo after employee name…", meta: "http://meta.stackexchange.com/quest…", match: "", exclude: "*://chat.*.com/*,SE1.0" } sox.common.js:16:13
SOX:  running markEmployees sox.common.js:16:13
SOX:  SOX Access Token: SET sox.common.js:16:13
SOX:  Appearance sox.common.js:16:13
SOX:  metaChatBlogStackExchangeButton sox.common.js:16:13
SOX:  Object { name: "metaChatBlogStackExchangeButton", desc: "Show meta and chat buttons on hover…", meta: "http://meta.stackexchange.com/quest…", match: "", exclude: "" } sox.common.js:16:13
SOX:  running metaChatBlogStackExchangeButton sox.common.js:16:13
SOX:  Appearance sox.common.js:16:13
SOX:  metaNewQuestionAlert sox.common.js:16:13
SOX:  Object { name: "metaNewQuestionAlert", desc: "Add a mod diamond to the topbar to …", meta: "http://meta.stackexchange.com/quest…", match: "", exclude: "*://chat.*.com/*,SE1.0" } sox.common.js:16:13
SOX:  running metaNewQuestionAlert sox.common.js:16:13
SOX:  Appearance sox.common.js:16:13
SOX:  scrollToTop sox.common.js:16:13
SOX:  Object { name: "scrollToTop", desc: "Add Scroll To Top button", extended_description: "This feature adds a 'scroll to top'…", meta: "", match: "", exclude: "*://chat.*.com/*" } sox.common.js:16:13
SOX:  running scrollToTop sox.common.js:16:13
SOX:  Appearance sox.common.js:16:13
SOX:  standOutDupeCloseMigrated sox.common.js:16:13
SOX:  Object { name: "standOutDupeCloseMigrated", desc: "Add highlighted tags to closed/on h…", extended_description: "Adds a coloured box at the end of a…", meta: "http://meta.stackexchange.com/quest…", match: "", exclude: "*://chat.*.com/*,SE1.0" } sox.common.js:16:13
SOX:  running standOutDupeCloseMigrated sox.common.js:16:13
SOX:  observe: #user-tab-questions, #question-mini-list sox.common.js:16:13
SOX:  undefined sox.common.js:16:13
SOX:  Appearance sox.common.js:16:13
SOX:  tabularReviewerStats sox.common.js:16:13
SOX:  Object { name: "tabularReviewerStats", desc: "Display reviewer stats on /review/s…", meta: "http://meta.stackexchange.com/q/276…", match: "*://*.com/review/suggested-edits/*", exclude: "" } sox.common.js:16:13
SOX:  Comments sox.common.js:16:13
SOX:  autoShowCommentImages sox.common.js:16:13
SOX:  Object { name: "autoShowCommentImages", desc: "View linked images (to imgur) in co…", meta: "", match: "*://*/questions*", exclude: "SE1.0" } sox.common.js:16:13
SOX:  running autoShowCommentImages sox.common.js:16:13
SOX:  observe: .new_comment sox.common.js:16:13
SOX:  NodeList [ <table>, <table>, <table>, <table>, <table>, <table>, <table>, <table>, <table>, <table>, 1 more… ] sox.common.js:16:13
SOX:  Comments sox.common.js:16:13
SOX:  commentReplies sox.common.js:16:13
SOX:  Object { name: "commentReplies", desc: "Add reply links to comments for qui…", meta: "http://meta.stackexchange.com/quest…", match: "*://*/questions*", exclude: "SE1.0" } sox.common.js:16:13
SOX:  running commentReplies sox.common.js:16:13
SOX:  observe: .new_comment sox.common.js:16:13
SOX:  undefined sox.common.js:16:13
SOX:  Comments sox.common.js:16:13
SOX:  commentShortcuts sox.common.js:16:13
SOX:  Object { name: "commentShortcuts", desc: "Use Ctrl+I,B,K (to italicise, bolde…", meta: "http://meta.stackexchange.com/quest…", match: "*://*/questions*", exclude: "SE1.0" } sox.common.js:16:13
SOX:  running commentShortcuts sox.common.js:16:13
SOX:  Comments sox.common.js:16:13
SOX:  confirmNavigateAway sox.common.js:16:13
SOX:  Object { name: "confirmNavigateAway", desc: "Add a confirmation dialog when navi…", meta: "http://meta.stackexchange.com/quest…", match: "*://*/questions*", exclude: "SE1.0" } sox.common.js:16:13
SOX:  running confirmNavigateAway sox.common.js:16:13
SOX:  Comments sox.common.js:16:13
SOX:  showCommentScores sox.common.js:16:13
SOX:  Object { name: "showCommentScores", desc: "Show your comment and comment repli…", meta: "http://meta.stackexchange.com/quest…", match: "*://*/users/*", exclude: "SE1.0" } sox.common.js:16:13
SOX:  Comments sox.common.js:16:13
SOX:  hiddenCommentsIndicator sox.common.js:16:13
SOX:  Object { name: "hiddenCommentsIndicator", desc: "Add a darker border underneath comm…", meta: "http://meta.stackoverflow.com/q/296…", match: "*://*/questions*", exclude: "SE1.0" } sox.common.js:16:13
SOX:  running hiddenCommentsIndicator sox.common.js:16:13
SOX:  Editing sox.common.js:16:13
SOX:  addSBSBtn sox.common.js:16:13
SOX:  Object { name: "addSBSBtn", desc: "Add a button to the editor toolbar …", extended_description: "An 'SBS' button is added to the rig…", meta: "http://meta.stackexchange.com/quest…", match: "", exclude: "*://chat.*.com/*,SE1.0" } sox.common.js:16:13
SOX:  running addSBSBtn sox.common.js:16:13
SOX:  observe: #wmd-redo-button-887338 sox.common.js:16:13
SOX:  undefined sox.common.js:16:13
SOX:  observe: #wmd-redo-button-858531 sox.common.js:16:13
SOX:  undefined sox.common.js:16:13
SOX:  observe: #wmd-redo-button-853049 sox.common.js:16:13
SOX:  undefined sox.common.js:16:13
SOX:  observe: #wmd-redo-button-858527 sox.common.js:16:13
SOX:  undefined sox.common.js:16:13
SOX:  observe: #wmd-redo-button-735293 sox.common.js:16:13
SOX:  undefined sox.common.js:16:13
SOX:  observe: li[id^="wmd-redo-button"] sox.common.js:16:13
SOX:  undefined sox.common.js:16:13
SOX:  observe: .wmd-preview.sbs-on sox.common.js:16:13
SOX:  undefined sox.common.js:16:13
SOX:  Editing sox.common.js:16:13
SOX:  editComment sox.common.js:16:13
SOX:  Object { name: "editComment", desc: "Pre-defined edit comment options (c…", meta: "http://meta.stackexchange.com/quest…", match: "", exclude: "*://chat.*.com/*,SE1.0" } sox.common.js:16:13
SOX:  running editComment sox.common.js:16:13
SOX:  Editing sox.common.js:16:13
SOX:  editReasonTooltip sox.common.js:16:13
SOX:  Object { name: "editReasonTooltip", desc: "Add a tooltip to posts showing the …", extended_description: "When a post is edited, the editor i…", meta: "http://meta.stackexchange.com/quest…", match: "*://*/questions*", exclude: "SE1.0" } sox.common.js:16:13
SOX:  running editReasonTooltip sox.common.js:16:13
SOX:  Editing sox.common.js:16:13
SOX:  enhancedEditor sox.common.js:16:13
SOX:  Object { name: "enhancedEditor", desc: "Add more features to the markdown e…", meta: "", match: "*://*/questions*,*://*/review*", exclude: "SE1.0" } sox.common.js:16:13
SOX:  running enhancedEditor sox.common.js:16:13
SOX:  observe: li[id^="wmd-redo-button"], textarea[id^="wmd-input"] sox.common.js:16:13
SOX:  undefined sox.common.js:16:13
SOX:  Editing sox.common.js:16:13
SOX:  kbdAndBullets sox.common.js:16:13
SOX:  Object { name: "kbdAndBullets", desc: "Add KBD and list buttons to editor …", meta: "http://meta.stackexchange.com/quest…", match: "", exclude: "*://chat.*.com/*,SE1.0" } sox.common.js:16:13
SOX:  running kbdAndBullets sox.common.js:16:13
SOX:  observe: [id^="wmd-redo-button"] sox.common.js:16:13
SOX:  undefined sox.common.js:16:13
SOX:  Editing sox.common.js:16:13
SOX:  titleEditDiff sox.common.js:16:13
SOX:  Object { name: "titleEditDiff", desc: "Make title edits show separately ra…", meta: "http://meta.stackexchange.com/quest…", match: "*://*.com/review/suggested-edits*", exclude: "" } sox.common.js:16:13
SOX:  Editing sox.common.js:16:13
SOX:  inlineEditorEverywhere sox.common.js:16:13
SOX:  Object { name: "inlineEditorEverywhere", desc: "Inline editor regardless of reputat…", extended_description: "Enables the inline editor on all si…", meta: "", match: "*://*/questions*", exclude: "" } sox.common.js:16:13
SOX:  running inlineEditorEverywhere sox.common.js:16:13
SOX:  inlineEditorEverywhere error: sox.Stack.using not found sox.common.js:28:13
SOX:  inlineEditorEverywhere: Stack object: sox.common.js:16:13
SOX:  Object { init: StackExchange.init</<(n, s), debug: Object, initialized: Object, ready: StackExchange.ready(e), using: v(e, n, a, i), ifUsing: b(e, t, n), loadJsFile: StackExchange.loadJsFile(e, t), loadJqueryUi: StackExchange.loadJqueryUi(), helpers: Object, switchMobile: StackExchange.switchMobile(e), 29 more… } sox.common.js:16:13
SOX:  Editing sox.common.js:16:13
SOX:  downvotedPostsEditAlert sox.common.js:16:13
SOX:  Object { name: "downvotedPostsEditAlert", desc: "Add a notification to your inbox wh…", meta: "http://meta.stackexchange.com/q/165…", match: "", exclude: "" } sox.common.js:16:13
SOX:  running downvotedPostsEditAlert sox.common.js:16:13
SOX:  downvotedPostsEditAlert posts to check sox.common.js:16:13
SOX:  Object { 11990: Object } sox.common.js:16:13
SOX:  downvotedPostsEditAlert notifications sox.common.js:16:13
SOX:  Object { 11990: Object } sox.common.js:16:13
SOX:  downvotedPostsEditAlert addEditNotification editTime sox.common.js:16:13
SOX:  1482548454 sox.common.js:16:13
SOX:  SOX Access Token: SET sox.common.js:16:13
SOX:  "Getting From API with URL: https://api.stackexchange.com/2.2/posts/11990/revisions?order=desc&sort=creation?pagesize=1&site=meta&key=lL1S1jr2m*DRwOvXMPp26g((&access_token=smhSimsp1MHul(yestw7XA))" sox.common.js:16:13
SOX:  SOX Access Token: SET sox.common.js:16:13
GET 
https://cdn.sstatic.net/Js/post-validation.en.js [HTTP/2.0 304 Not Modified 15ms]
GET 
http://cdn-prom.sstatic.net/WinterBash/js/qa-wb.js [HTTP/1.1 304 Not Modified 39ms]
GET 
https://cdn.sstatic.net/Js/external-editor.en.js [HTTP/2.0 304 Not Modified 18ms]
GET 
https://i.stack.imgur.com/Ohyu2.png [HTTP/1.1 304 Not Modified 24ms]
GET 
https://i.stack.imgur.com/vBJkv.png [HTTP/1.1 304 Not Modified 21ms]
GET 
https://i.stack.imgur.com/2QBB2.png [HTTP/1.1 304 Not Modified 21ms]
GET 
https://i.stack.imgur.com/jt6hT.png [HTTP/1.1 304 Not Modified 21ms]
GET 
XHR 
http://superuser.com/posts/735293/ivc/1f7b [HTTP/1.1 204 No Content 25ms]
GET 
https://rawgit.com/shu8/SE-Answers_scripts/master/dupeClosedMigratedCSS.css [HTTP/2.0 304 Not Modified 41ms]
Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help http://xhr.spec.whatwg.org/ jquery-2.1.4.min.js:4:14346
GET 
https://www.gravatar.com/avatar/e88cb2b3858ca0df735806f1a8476b23 [HTTP/2.0 304 Not Modified 15ms]
GET 
https://www.gravatar.com/avatar/27f497f619785fb64129b9472c101a5a [HTTP/2.0 304 Not Modified 14ms]
GET 
https://www.gravatar.com/avatar/082d6a8bed92991450502419bdf5d420 [HTTP/2.0 304 Not Modified 14ms]
GET 
https://i.stack.imgur.com/eSD8M.jpg [HTTP/1.1 304 Not Modified 20ms]
GET 
https://i.stack.imgur.com/2cvw3.jpg [HTTP/1.1 304 Not Modified 25ms]
GET 
http://static.adzerk.net/Extensions/adFeedback.js [HTTP/1.1 304 Not Modified 21ms]
GET 
http://static.adzerk.net/Extensions/adFeedback.css [HTTP/1.1 304 Not Modified 25ms]
GET 
XHR 
https://query.yahooapis.com/v1/public/yql [HTTP/2.0 200 OK 95ms]
GET 
XHR 
https://api.stackexchange.com/2.2/users/311612;83283;24010;426221;19943;316136 [HTTP/1.1 200 OK 38ms]
GET 
XHR 
https://api.stackexchange.com/2.2/questions [HTTP/1.1 200 OK 63ms]
GET 
XHR 
http://superuser.com/posts/858527/revisions [HTTP/1.1 200 OK 67ms]
GET 
XHR 
https://api.stackexchange.com/2.2/posts/11990/revisions [HTTP/1.1 200 OK 95ms]
SOX:  "SOX editReasonTooltip URL: http://superuser.com/posts/858527/revisions" sox.common.js:16:13
SOX:  SOX editReasonTooltip text: deleted 6 characters in body sox.common.js:16:13
SOX:  SOX editReasonTooltip: adding to tooltip sox.common.js:16:13
SOX:  SOX editReasonTooltip: finished adding to tooltip sox.common.js:16:13
SOX:  SOX editReasonTooltip: tooltip is now: deleted 6 characters in body sox.common.js:16:13
SOX:  Object { 11990: Object } sox.common.js:16:13
SOX:  downvotedPostsEditAlert: Last Checked Time: 1482548962986 sox.common.js:16:13
SOX:  WebSocket { url: "wss://qa.sockets.stackexchange.com/", readyState: 0, bufferedAmount: 0, onopen: null, onerror: null, onclose: null, extensions: "", protocol: "", onmessage: function (), binaryType: "blob" } sox.common.js:16:13
SOX:  0 sox.common.js:16:13
SOX:  Flags sox.common.js:16:13
SOX:  flagOutcomeTime sox.common.js:16:13
SOX:  Object { name: "flagOutcomeTime", desc: "Show the flag outcome time when vie…", meta: "", match: "", exclude: "*://chat.*.com/*,SE1.0" } sox.common.js:16:13
SOX:  running flagOutcomeTime sox.common.js:16:13
SOX:  Flags sox.common.js:16:13
SOX:  flagPercentages sox.common.js:16:13
SOX:  Object { name: "flagPercentages", desc: "Show flagging percentages for each …", meta: "", match: "", exclude: "*://chat.*.com/*,SE1.0" } sox.common.js:16:13
SOX:  running flagPercentages sox.common.js:16:13
SOX:  Flags sox.common.js:16:13
SOX:  flagPercentageBar sox.common.js:16:13
SOX:  Object { name: "flagPercentageBar", desc: "Show the total percentage of helpfu…", meta: "http://meta.stackoverflow.com/quest…", match: "", exclude: "*://chat.*.com/*,SE1.0" } sox.common.js:16:13
SOX:  running flagPercentageBar sox.common.js:16:13
SOX:  Sidebar sox.common.js:16:13
SOX:  hideHireMe sox.common.js:16:13
SOX:  Object { name: "hideHireMe", desc: "Hide the Looking for a Job module", meta: "", match: "", exclude: "*://chat.*.com/*" } sox.common.js:16:13
SOX:  running hideHireMe sox.common.js:16:13
SOX:  Sidebar sox.common.js:16:13
SOX:  linkedToFrom sox.common.js:16:13
SOX:  Object { name: "linkedToFrom", desc: "Add an arrow to linked posts in the…", meta: "http://meta.stackexchange.com/q/276…", match: "*://*/questions*", exclude: "SE1.0" } sox.common.js:16:13
SOX:  running linkedToFrom sox.common.js:16:13
SOX:  Chat sox.common.js:16:13
SOX:  chatEasyAccess sox.common.js:16:13
SOX:  Object { name: "chatEasyAccess", desc: "Add buttons to user profiles to cha…", meta: "http://meta.stackexchange.com/q/203…", match: "*://chat.*.com/*", exclude: "" } sox.common.js:16:13
SOX:  Chat sox.common.js:16:13
SOX:  replyToOwnChatMessages sox.common.js:16:13
SOX:  Object { name: "replyToOwnChatMessages", desc: "Add reply signs to your own chat me…", meta: "", match: "*://chat.*.com/*", exclude: "" } sox.common.js:16:13
SOX:  Chat sox.common.js:16:13
SOX:  renameChat sox.common.js:16:13
SOX:  Object { name: "renameChat", desc: "Prepend 'Chat - ' to chat tabs' tit…", meta: "http://meta.stackexchange.com/quest…", match: "*://chat.*.com/*", exclude: "" } sox.common.js:16:13
SOX:  Voting sox.common.js:16:13
SOX:  grayOutVotes sox.common.js:16:13
SOX:  Object { name: "grayOutVotes", desc: "Gray out deleted vote buttons", meta: "http://meta.stackexchange.com/a/174…", match: "*://*/questions*", exclude: "SE1.0" } sox.common.js:16:13
SOX:  running grayOutVotes sox.common.js:16:13
SOX:  Voting sox.common.js:16:13
SOX:  disableOwnPostVoteButtons sox.common.js:16:13
SOX:  Object { name: "disableOwnPostVoteButtons", desc: "Disable vote buttons on your own po…", meta: "", match: "*://*/questions*", exclude: "SE1.0" } sox.common.js:16:13
SOX:  running disableOwnPostVoteButtons sox.common.js:16:13
SOX:  Unsorted sox.common.js:16:13
SOX:  alwaysShowImageUploadLinkBox sox.common.js:16:13
SOX:  Object { name: "alwaysShowImageUploadLinkBox", desc: "Always show the 'Link from the web'…", extended_description: "Removes the 'you can also provide a…", meta: "http://meta.stackoverflow.com/q/306…", match: "*://*/questions*", exclude: "SE1.0" } sox.common.js:16:13
SOX:  running alwaysShowImageUploadLinkBox sox.common.js:16:13
SOX:  observe: .image-upload form sox.common.js:16:13
SOX:  undefined sox.common.js:16:13
SOX:  Unsorted sox.common.js:16:13
SOX:  linkedPostsInline sox.common.js:16:13
SOX:  Object { name: "linkedPostsInline", desc: "Display linked posts inline by clic…", meta: "", match: "*://*/questions*", exclude: "SE1.0" } sox.common.js:16:13
SOX:  running linkedPostsInline sox.common.js:16:13
SOX:  Unsorted sox.common.js:16:13
SOX:  parseCrossSiteLinks sox.common.js:16:13
SOX:  Object { name: "parseCrossSiteLinks", desc: "Parse titles to links cross-SE-sites", meta: "http://meta.stackexchange.com/quest…", match: "*://*/questions*", exclude: "SE1.0" } sox.common.js:16:13
SOX:  running parseCrossSiteLinks sox.common.js:16:13
SOX:  Unsorted sox.common.js:16:13
SOX:  quickAuthorInfo sox.common.js:16:13
SOX:  Object { name: "quickAuthorInfo", desc: "Show when the post's author was las…", meta: "", match: "*://*/questions*", exclude: "SE1.0" } sox.common.js:16:13
SOX:  running quickAuthorInfo sox.common.js:16:13
SOX:  Could not find user user link for:  sox.common.js:40:13
SOX:  Object { context: <div#answer-858531.answer.deleted-answer>, length: 1, 1 more… } sox.common.js:40:13
SOX:  Could not find user user link for:  sox.common.js:40:13
SOX:  Object { context: <div#answer-853049.answer.deleted-answer>, length: 1, 1 more… } sox.common.js:40:13
SOX:  quickAuthorInfo answerer IDs sox.common.js:16:13
SOX:  Object { 311612: "Quojil", 316136: "ᔕᖺᘎᕊ", 426221: "Hatesmanagedchromebookstoo" } sox.common.js:16:13
SOX:  quickAuthorInfo API call parameters sox.common.js:16:13
SOX:  users sox.common.js:16:13
SOX:  311612;316136;426221 sox.common.js:16:13
SOX:  superuser sox.common.js:16:13
SOX:  SOX Access Token: SET sox.common.js:16:13
SOX:  "Getting From API with URL: https://api.stackexchange.com/2.2/users/311612;316136;426221?order=desc&sort=creation&site=superuser&key=lL1S1jr2m*DRwOvXMPp26g((&access_token=smhSimsp1MHul(yestw7XA))" sox.common.js:16:13
SOX:  SOX Access Token: SET sox.common.js:16:13
The object cannot be linked to the inspector without a toolbox console-output.js:3245:0
TypeError: d.items[0] is undefined sox.features.js:1441:25
GET 
https://qa.sockets.stackexchange.com/ [HTTP/1.1 101 Switching Protocols 157ms]
GET 
https://cdn.sstatic.net/Js/wmd.en.js [HTTP/2.0 304 Not Modified 14ms]
GET 
http://cdn-prom.sstatic.net/WinterBash/css/wb-include.css [HTTP/1.1 304 Not Modified 33ms]
GET 
XHR 
https://api.stackexchange.com/2.2/users/311612;316136;426221 [HTTP/1.1 200 OK 37ms]
SOX:  quickAuthorInfo api dump sox.common.js:16:13
SOX:  Object { items: Array[3], has_more: false, quota_max: 10000, quota_remaining: 9994 } sox.common.js:16:13
SOX:  quickAuthorInfor userdetailsfromapi sox.common.js:16:13
SOX:  Object { 311612: Object, 316136: Object, 426221: Object } sox.common.js:16:13
SOX:  current post sox.common.js:16:13
SOX:  Object { context: <div#question.question>, length: 1, 1 more… } sox.common.js:16:13
SOX:  quickAuthorInfo addLastSeen(): current id sox.common.js:16:13
SOX:  311612 sox.common.js:16:13
SOX:  quickAuthorInfo addLastSeen(): userdetailscurrent id sox.common.js:16:13
SOX:  Object { last_seen: 1428265514000, type: "registered" } sox.common.js:16:13
SOX:  current post sox.common.js:16:13
SOX:  Object { context: <div#answer-887338.answer>, length: 1, 1 more… } sox.common.js:16:13
SOX:  quickAuthorInfo addLastSeen(): current id sox.common.js:16:13
SOX:  426221 sox.common.js:16:13
SOX:  quickAuthorInfo addLastSeen(): userdetailscurrent id sox.common.js:16:13
SOX:  Object { last_seen: 1425901113000, type: "unregistered" } sox.common.js:16:13
SOX:  current post sox.common.js:16:13
SOX:  Object { context: <div#answer-858531.answer.deleted-answer>, length: 1, 1 more… } sox.common.js:16:13
SOX:  current post sox.common.js:16:13
SOX:  Object { context: <div#answer-853049.answer.deleted-answer>, length: 1, 1 more… } sox.common.js:16:13
SOX:  current post sox.common.js:16:13
SOX:  Object { context: <div#answer-858527.answer.deleted-answer>, length: 1, 1 more… } sox.common.js:16:13
SOX:  quickAuthorInfo addLastSeen(): current id sox.common.js:16:13
SOX:  undefined sox.common.js:16:13
SOX:  quickAuthorInfo addLastSeen(): userdetailscurrent id sox.common.js:16:13
SOX:  undefined sox.common.js:16:13
SOX:  observe: .new_comment sox.common.js:16:13
SOX:  NodeList [ <table>, <table>, <table>, <table>, <table>, <table>, <table>, <table>, <table>, <table>, 1 more… ] sox.common.js:16:13
SOX:  Unsorted sox.common.js:16:13
SOX:  shareLinksMarkdown sox.common.js:16:13
SOX:  Object { name: "shareLinksMarkdown", desc: "Change 'share' link to format of [p…", extended_description: "When you click 'share' under a post…", meta: "http://meta.stackexchange.com/quest…", match: "*://*/questions*", exclude: "SE1.0" } sox.common.js:16:13
SOX:  running shareLinksMarkdown sox.common.js:16:13
SOX:  observe: .share-tip sox.common.js:16:13
SOX:  undefined sox.common.js:16:13
SOX:  Unsorted sox.common.js:16:13
SOX:  warnNotLoggedIn sox.common.js:16:13
SOX:  Object { name: "warnNotLoggedIn", desc: "Warn you when you are not logged in", meta: "", match: "", exclude: "*://chat.*.com/*,SE1.0" } sox.common.js:16:13
SOX:  running warnNotLoggedIn sox.common.js:16:13
SOX:  Unsorted sox.common.js:16:13
SOX:  showMetaReviewCount sox.common.js:16:13
SOX:  Object { name: "showMetaReviewCount", desc: "Add how many reviews are available …", meta: "", match: "*://*/review", exclude: "*://meta.*.com/*" } sox.common.js:16:13
The object cannot be linked to the inspector without a toolbox console-output.js:3245:0
GET 
http://cdn-prom.sstatic.net/WinterBash/js/theactualhats.js [HTTP/1.1 304 Not Modified 19ms]
SOX:  fire: target: [object HTMLTextAreaElement] sox.common.js:16:13
GET 
https://qa.sockets.stackexchange.com/ [HTTP/1.1 101 Switching Protocols 137ms]
GET 
https://cdn.sstatic.net/Sites/superuser/img/wmd-buttons.svg [HTTP/2.0 304 Not Modified 12ms]
GET 
http://engine.adzerk.net/i.gif [HTTP/1.1 200 OK 98ms]
The object cannot be linked to the inspector without a toolbox console-output.js:3245:0
SOX:  websocket opened sox.common.js:16:13
SOX:  downvotedPostsEditAlert: sending websocket message: undefined-question-11990 sox.common.js:16:13
GET 
http://stackexchange.com/ads/launched-question/js [HTTP/1.1 200 OK 33ms]
GET 
https://cdn.sstatic.net/stackexchange/Img/launched-ads/serverfault.png [HTTP/2.0 304 Not Modified 17ms]
GET 
XHR 
https://l.ghostery.com/api/page/ [HTTP/1.1 204 No Content 21ms]
GET 
XHR 
https://l.ghostery.com/api/census [HTTP/1.1 204 No Content 23ms]
GET 
XHR 
https://l.ghostery.com/api/census [HTTP/1.1 204 No Content 25ms]
GET 
XHR 
https://l.ghostery.com/api/census [HTTP/1.1 204 No Content 26ms]
GET 
XHR 
https://l.ghostery.com/api/census [HTTP/1.1 204 No Content 26ms]
GET 
XHR 
https://l.ghostery.com/api/census [HTTP/1.1 204 No Content 29ms]
GET 
XHR 
https://l.ghostery.com/api/census [HTTP/1.1 204 No Content 33ms]
GET 
XHR 
https://l.ghostery.com/api/census [HTTP/1.1 204 No Content 35ms]
GET 
XHR 
https://l.ghostery.com/api/census [HTTP/1.1 204 No Content 52ms]
GET 
XHR 
https://l.ghostery.com/api/census [HTTP/1.1 204 No Content 51ms]
GET 
XHR 
https://l.ghostery.com/api/census [HTTP/1.1 204 No Content 48ms]
GET 
XHR 
https://l.ghostery.com/api/census [HTTP/1.1 204 No Content 45ms]
GET 
XHR 
https://l.ghostery.com/api/census [HTTP/1.1 204 No Content 51ms]
GET 
XHR 
https://l.ghostery.com/api/census [HTTP/1.1 204 No Content 66ms]
GET 
XHR 
https://l.ghostery.com/api/census [HTTP/1.1 204 No Content 72ms]
GET 
XHR 
https://l.ghostery.com/api/census [HTTP/1.1 204 No Content 94ms]
GET 
XHR 
https://l.ghostery.com/api/census [HTTP/1.1 204 No Content 93ms]
GET 
XHR 
https://l.ghostery.com/api/census [HTTP/1.1 204 No Content 88ms]
GET 
XHR 
https://l.ghostery.com/api/census [HTTP/1.1 204 No Content 87ms]
GET 
XHR 
https://l.ghostery.com/api/census [HTTP/1.1 204 No Content 86ms]
GET 
XHR 
https://l.ghostery.com/api/census [HTTP/1.1 204 No Content 82ms]
GET 
XHR 
https://l.ghostery.com/api/census [HTTP/1.1 204 No Content 105ms]
GET 
XHR 
https://l.ghostery.com/api/census [HTTP/1.1 204 No Content 121ms]
GET 
XHR 
https://l.ghostery.com/api/census [HTTP/1.1 204 No Content 119ms]
GET 
XHR 
https://l.ghostery.com/api/census [HTTP/1.1 204 No Content 118ms]
mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create panel.js:5816:3
Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help http://xhr.spec.whatwg.org/ panel.js:3525:3
not well-formed messages.json:1:1
```

---

### Steps to reproduce

---

### Features Enabled 

    ["Appearance-addAuthorNameToInboxNotifications","Appearance-alignBadgesByClass","Appearance-answerTagsSearch","Appearance-colorAnswerer","Appearance-fixedTopbar","Appearance-isQuestionHot","Appearance-markEmployees","Appearance-metaChatBlogStackExchangeButton","Appearance-metaNewQuestionAlert","Appearance-scrollToTop","Appearance-standOutDupeCloseMigrated","Appearance-tabularReviewerStats","Comments-autoShowCommentImages","Comments-commentReplies","Comments-commentShortcuts","Comments-confirmNavigateAway","Comments-showCommentScores","Comments-hiddenCommentsIndicator","Editing-addSBSBtn","Editing-editComment","Editing-editReasonTooltip","Editing-enhancedEditor","Editing-kbdAndBullets","Editing-titleEditDiff","Editing-inlineEditorEverywhere","Editing-downvotedPostsEditAlert","Flags-flagOutcomeTime","Flags-flagPercentages","Flags-flagPercentageBar","Sidebar-hideHireMe","Sidebar-linkedToFrom","Chat-chatEasyAccess","Chat-replyToOwnChatMessages","Chat-renameChat","Voting-grayOutVotes","Voting-disableOwnPostVoteButtons","Unsorted-alwaysShowImageUploadLinkBox","Unsorted-linkedPostsInline","Unsorted-parseCrossSiteLinks","Unsorted-quickAuthorInfo","Unsorted-shareLinksMarkdown","Unsorted-warnNotLoggedIn","Unsorted-showMetaReviewCount"]

**Comment by shu8** [comment]
@fixer1234 should be fixed in [dev k](https://github.com/soscripted/sox/raw/dev/sox.user.js)

**Comment by Franck-Dernoncourt** [comment]
Thanks,  the fix worked for me.

**Comment by fixer1234** [comment]
@shu8 The fix didn't work for me, those features are still gone.  Reopen?  Need new console output?

**Comment by Franck-Dernoncourt** [comment]
hmm I see Ask Question works but not Your Answer box. Sorry I should have checked both (I was just asking question this morning :))

**Comment by fixer1234** [comment]
I hadn't rechecked Ask Question before posting, but that one also still doesn't work on my system.

**Comment by Franck-Dernoncourt** [comment]
Interesting. I use V2.0.3DEVL

**Comment by shu8** [comment]
It'll probably be a Firefox thing again :P

I'll check it out as soon as possible :)

**Comment by jcollum** [comment]
Confirmed on 2.0.2. The SBS Editor button was there a couple of days ago. Now it's gone.

**Comment by shu8** [comment]
@fixer1234 @jcollum @Franck-Dernoncourt Please could you try again in [dev m](https://github.com/soscripted/sox/raw/dev/sox.user.js)? :)

**Comment by jcollum** [comment]
Looks good to me.

**Comment by Franck-Dernoncourt** [comment]
doesn't work for me in the "your answer" edit box. (Google Chrome)

![image](https://cloud.githubusercontent.com/assets/15331/21485279/cf4a80fc-cb6e-11e6-8126-7bc590f0058b.png)

**Comment by jcollum** [comment]
I'm seeing it in both.

**Comment by Franck-Dernoncourt** [comment]
are you on chrome?

**Comment by fixer1234** [comment]
Dev M loaded, Firefox/Greasemonkey.  No Kbd/List or SBS on Q/A edit, Your Answer, or Ask Question.  Also missing on Improve Edit in Edit review queue.

**Comment by shu8** [comment]
@fixer1234 you're right. it's FF, again 😞 

working on a fix

**Comment by shu8** [comment]
@fixer1234 @Franck-Dernoncourt @jcollum ok.... should 🤞  be fixed on Chrome and FF in [dev n](https://github.com/soscripted/sox/raw/dev/sox.user.js) now...

please can you confirm?

**Comment by Franck-Dernoncourt** [comment]
thanks, it works with me (Google Chrome), both when asking a question or
answering a question.

**Comment by fixer1234** [comment]
@shu8 Dev N loaded, Firefox/Greasemonkey.  The buttons are back for me on Q/A post edits, Ask Question, Your Answer, and review queue edits.

If I'm reading the history right, I think everybody who reported the issue has said it's now working, so I'll close it.

**Comment by fixer1234** [comment]
@shu8 Loaded Dev P.  All of the editor additions (kbd/list, SBS,  Find&Replace/Auto-correct) are missing in all edit locations (Q/A post, Ask Question, Your Answer, review queue).

**Comment by shu8** [comment]
@fixer1234 sorry, same reason as https://github.com/soscripted/sox/issues/191#issuecomment-269383592

fixed in [dev q](https://github.com/soscripted/sox/raw/dev/sox.user.js)

**Comment by fixer1234** [comment]
@shu8 OK.  There returned in Dev Q.

**Comment by fixer1234** [comment]
@shu8 The Kbd/List buttons are missing in v2.0.4 in the review queue edit window (only there, it's fine on Q/A edits, Ask Question, and Your Answer).  I didn't grab console output while I was there.  If you need that, I'll capture it the next time I edit in the review queue.

**Comment by shu8** [comment]
@fixer1234 fixed in [dev 2.0.5](https://github.com/soscripted/sox/raw/dev/sox.user.js)

**Comment by fixer1234** [comment]
@shu8 Confirmed.
