### ISSUE TITLE
Clicking "Edit" on a question freezes the tab.

### ISSUE THREAD

**Issue by crackwitz** [soscripted/sox#514]
**Describe the bug**
Hit 'Edit' on any question, then the tab freezes from some infinite loop.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to any question (pick from [questions page](https://stackoverflow.com/questions?tab=Newest))
2. Click on 'Edit' which is right under the question
3. Throbber animation next to the 'Edit' appears, but the entire tab refuses to respond to any input, including mouse hovers and attempts to close the tab in some ways

**SOX errors logged in console**
I managed to grab part of the log. This here repeats hundreds of times a second:
```
userscript.html?name=Stack-Overflow-Extras-SOX.user.js&id=01210d23-bf2a-430b-ab67-11d264c6a0e1:269 SOX: sox-edit-window event triggered
05:03:40.660 userscript.html?name=Stack-Overflow-Extras-SOX.user.js&id=01210d23-bf2a-430b-ab67-11d264c6a0e1:269 SOX: fire: target
05:03:40.661 userscript.html?name=Stack-Overflow-Extras-SOX.user.js&id=01210d23-bf2a-430b-ab67-11d264c6a0e1:269 SOX: w.fn.init {0: textarea#wmd-input-79777399.wmd-input.s-input.bar0.js-post-body-field, 1: textarea#wmd-input.wmd-input.s-input.bar0.js-post-body-field.processed, length: 2, prevObject: w.fn.init}
05:03:40.661 userscript.html?name=Stack-Overflow-Extras-SOX.user.js&id=01210d23-bf2a-430b-ab67-11d264c6a0e1:269 SOX: sox-edit-window event triggered
05:03:40.667 userscript.html?name=Stack-Overflow-Extras-SOX.user.js&id=01210d23-bf2a-430b-ab67-11d264c6a0e1:269 SOX: fire: target
05:03:40.668 userscript.html?name=Stack-Overflow-Extras-SOX.user.js&id=01210d23-bf2a-430b-ab67-11d264c6a0e1:269 SOX: w.fn.init {0: textarea#wmd-input-79777399.wmd-input.s-input.bar0.js-post-body-field, 1: textarea#wmd-input.wmd-input.s-input.bar0.js-post-body-field.processed, length: 2, prevObject: w.fn.init}
05:03:40.669 userscript.html?name=Stack-Overflow-Extras-SOX.user.js&id=01210d23-bf2a-430b-ab67-11d264c6a0e1:269 SOX: sox-edit-window event triggered
05:03:40.675 userscript.html?name=Stack-Overflow-Extras-SOX.user.js&id=01210d23-bf2a-430b-ab67-11d264c6a0e1:269 SOX: fire: target
05:03:40.676 userscript.html?name=Stack-Overflow-Extras-SOX.user.js&id=01210d23-bf2a-430b-ab67-11d264c6a0e1:269 SOX: w.fn.init {0: textarea#wmd-input-79777399.wmd-input.s-input.bar0.js-post-body-field, 1: textarea#wmd-input.wmd-input.s-input.bar0.js-post-body-field.processed, length: 2, prevObject: w.fn.init}
05:03:40.676 userscript.html?name=Stack-Overflow-Extras-SOX.user.js&id=01210d23-bf2a-430b-ab67-11d264c6a0e1:269 SOX: sox-edit-window event triggered
05:03:40.684 userscript.html?name=Stack-Overflow-Extras-SOX.user.js&id=01210d23-bf2a-430b-ab67-11d264c6a0e1:269 SOX: fire: target
05:03:40.686 userscript.html?name=Stack-Overflow-Extras-SOX.user.js&id=01210d23-bf2a-430b-ab67-11d264c6a0e1:269 SOX: 
```
**Expected behaviour**
No tab freezing and infinite loop.

**Environment**
- SOX 2.9.0DEV (as presented here: https://github.com/soscripted/sox/issues/513#issuecomment-3408125823 )
- Chrome, latest update or close to it by days
- Tampermonkey 5.4.0

**Comment by shu8** [comment]
Thanks for the bug report @crackwitz!

This should now be fixed in the latest [dev version v2.9.1](https://github.com/soscripted/sox/raw/dev/sox.user.js) - please let me know if it works!

**Comment by crackwitz** [comment]
`v2.9.1 DEV` still behaves the same way here. Maybe it's some kind of interference on my end. I have a few more userscripts and browser extensions. When the issue occurs, I see no "third party" logging in the console, only SOX. At least none of the other userscripts are to blame because the issue persists even if I disable all but SOX.

Deselecting the *"Pre-defined edit comment options (checkboxes)"* restores functionality.

I did see new checkboxes under some editor/input box recently (editing an *answer*?), after the update to v2.9.

**Comment by mezmi** [comment]
@shu8 You still on Discord?  If not, check email.

**Comment by crackwitz** [comment]
The freezing and event looping only happens when clicking "Edit" under a question (and with the checkboxes option active). It always works fine under answers.

**Comment by shu8** [comment]
@crackwitz sorry for the delay in getting back!

please could you share the full browser console output again when you use v2.9.1 dev?
