### ISSUE TITLE
Separate title edits still merged

### ISSUE THREAD

**Issue by fixer1234** [soscripted/sox#88]
**Installed Version: 1.X.X  |  Environment: Chrome/Tampermonkey**

**Expected Behavior**

> How do you expect the feature to work?
> Previous working versions of the feature showed an entire "before/after" comparison, rather than the edited segments.

**Actual Behavior**

> How is the feature currently behaving?
> The deleted and added segments are displayed.  See attached image.  Couldn't readily identify an edited title with a better mix of additions and deletions to ensure that this isn't intended behavior.

**Error Logs**

> SOX errors are logged to the browser console, if possible, please post those here.

![sox console output](https://cloud.githubusercontent.com/assets/10065766/17646584/327657ae-619e-11e6-92a9-1b2da2a7421a.png)

**Steps to reproduce**

> What steps did you take to reproduce the issue?
> Viewed title edit in edit history.

![sox title edit](https://cloud.githubusercontent.com/assets/10065766/17646577/d1915394-619d-11e6-9c58-3441d15f482b.png)

**Comment by shu8** [comment]
@fixer1234 I can't repro this, my FF and Chrome versions consistently show the separated diffs, eg. http://superuser.com/review/suggested-edits/533378. Could you try again after installing the [latest version](https://github.com/soscripted/sox/raw/fix/sox.user.js)?

**Comment by fixer1234** [comment]
@shu8, installed the new version.  The example you linked to displayed correctly, but I retried the example I posted above, and that still looks the same.  The console messages went on forever, so I cleared it and then reloaded the page and got new messages, so hopefully, this captured something relevant:

![capture](https://cloud.githubusercontent.com/assets/10065766/17652575/ba0c2518-624d-11e6-8367-380f5b5a0c9e.PNG)

**Comment by shu8** [comment]
@fixer1234 ah, looks like you're looking at the revision history.

this feature was mainly for use in the review, because it was very confusing to understand title edits when approving/rejecting edits. does it work for you [over here](http://superuser.com/review/suggested-edits/565441)?

If so, then the feature does *work*, but I do think it makes sense to try to do this same change in the edit history as well, but please could you confirm whether it is working as currently intended first?

**Comment by fixer1234** [comment]
@shu8, you're right.  OK, this does work in review.

**Comment by fixer1234** [comment]
@shu8, I spoke to soon.  The example you linked to worked.  I just opened an edit in the review queue and this example isn't:

![capture](https://cloud.githubusercontent.com/assets/10065766/17685016/53bd7078-632e-11e6-9338-044e65acdf13.PNG)

**Comment by shu8** [comment]
@fixer1234 I still can't repro this on FF either. Does this still happen?

**Comment by fixer1234** [comment]
Not sure if this was included in any changes on the "a" version, but just verified the problem on the previous newest, newer, new version.  Console output:

```
GET 
https://token.services.mozilla.com/1.0/sync/1.5 [HTTP/1.1 200 OK 353ms]
GET 
https://sync-325-us-west-2.sync.services.mozilla.com/1.5/42754320/info/collections [HTTP/1.1 200 OK 344ms]
POST 
https://sync-325-us-west-2.sync.services.mozilla.com/1.5/42754320/storage/tabs [HTTP/1.1 200 OK 136ms]
POST 
https://sync-325-us-west-2.sync.services.mozilla.com/1.5/42754320/storage/history [HTTP/1.1 200 OK 189ms]
The connection to wss://qa.sockets.stackexchange.com/ was interrupted while the page was loading. full.en.js:1:5142
GET 
http://superuser.com/posts/1116583/revisions [HTTP/1.1 200 OK 71ms]
GET 
http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js [HTTP/1.1 304 Not Modified 39ms]
GET 
http://cdn.sstatic.net/Js/stub.en.js [HTTP/1.1 304 Not Modified 24ms]
GET 
http://cdn.sstatic.net/Sites/superuser/all.css [HTTP/1.1 304 Not Modified 28ms]
GET 
https://i.stack.imgur.com/DPd3M.jpg [HTTP/1.1 304 Not Modified 62ms]
GET 
https://i.stack.imgur.com/DPd3M.jpg [HTTP/1.1 304 Not Modified 72ms]
GET 
https://www.gravatar.com/avatar/fb0c77a0a006eb85fdb143a3e2d4fb19 [HTTP/1.1 304 Not Modified 75ms]
GET 
https://www.gravatar.com/avatar/0b51840eb7be0a43d1d855b2f79bc0c8 [HTTP/1.1 304 Not Modified 85ms]
GET 
https://www.google-analytics.com/analytics.js [HTTP/2.0 304 Not Modified 27ms]
GET 
http://edge.quantserve.com/quant.js [HTTP/1.1 304 Not Modified 42ms]
GET 
http://b.scorecardresearch.com/beacon.js [HTTP/1.1 200 OK 41ms]
GET 
http://cdn.sstatic.net/img/share-sprite-new.svg [HTTP/1.1 304 Not Modified 14ms]
GET 
http://cdn.sstatic.net/Sites/superuser/img/sprites.svg [HTTP/1.1 304 Not Modified 22ms]
GET 
http://cdn.sstatic.net/Img/diff-icons/inline-html.png [HTTP/1.1 200 OK 18ms]
GET 
http://cdn.sstatic.net/Img/diff-icons/sidebyside-html.png [HTTP/1.1 304 Not Modified 28ms]
GET 
http://cdn.sstatic.net/Img/diff-icons/sidebyside-markdown.png [HTTP/1.1 304 Not Modified 20ms]
GET 
http://b.scorecardresearch.com/b [HTTP/1.1 204 No Content 15ms]
GET 
http://cdn.sstatic.net/Js/full.en.js [HTTP/1.1 304 Not Modified 12ms]
XrayWrapper denied access to property "ready" (reason: value is callable). See https://developer.mozilla.org/en-US/docs/Xray_vision for more information. Note that only the first denied property access from a given global object will be reported. sox.common.js:18:0
GET 
https://www.google-analytics.com/collect [HTTP/2.0 200 OK 14ms]
GET 
http://pixel.quantserve.com/pixel;r=2147152526;a=p-c1rF4kxgLUzNc;fpan=0;fpa=P0-2087723673-1465952398859;ns=0;ce=1;cm=;je=1;sr=2048x1152x24;enc=n;dst=1;et=1471986931629;tzo=240;ref=http%3A%2F%2Fsuperuser.com%2Fquestions%2F1116583%2Fhow-can-i-know-if-terminating-chkdsk-caused-corruption;url=http%3A%2F%2Fsuperuser.com%2Fposts%2F1116583%2Frevisions;ogl=type.website%2Cimage.http%3A%2F%2Fcdn%252Esstatic%252Enet%2FSites%2Fsuperuser%2Fimg%2Fapple-touch-icon%402%252Epng%3Fv%3De869e4459439%2Ctitle.Revisions%20to%20How%20can%20I%20know%20if%20terminating%20chkdsk%20caused%20corruption%3F%20%5Bduplicate%5D%2Cdescription.Q%26A%20for%20computer%20enthusiasts%20and%20power%20users%2Curl.http%3A%2F%2Fsuperuser%252Ecom%2Fposts%2F1116583%2Frevisions [HTTP/1.1 200 OK 31ms]
GET 
https://i.stack.imgur.com/DPd3M.jpg [HTTP/1.1 200 OK 0ms]
GET 
http://cdn.sstatic.net/Js/revisions.en.js [HTTP/1.1 304 Not Modified 11ms]
GET 
https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css [HTTP/2.0 304 Not Modified 102ms]
SOX:  initializing SOX dialog sox.common.js:63:17
GET 
https://i.stack.imgur.com/DPd3M.jpg [HTTP/1.1 200 OK 0ms]
GET 
http://cdn.sstatic.net/img/share-sprite-new.svg [HTTP/1.1 200 OK 0ms]
GET 
https://www.gravatar.com/avatar/fb0c77a0a006eb85fdb143a3e2d4fb19 [HTTP/1.1 200 OK 0ms]
GET 
http://cdn.sstatic.net/Sites/superuser/img/sprites.svg [HTTP/1.1 200 OK 0ms]
GET 
https://www.gravatar.com/avatar/0b51840eb7be0a43d1d855b2f79bc0c8 [HTTP/1.1 200 OK 0ms]
GET 
http://cdn.sstatic.net/Img/diff-icons/sidebyside-html.png [HTTP/1.1 200 OK 0ms]
GET 
http://cdn.sstatic.net/Img/diff-icons/sidebyside-markdown.png [HTTP/1.1 200 OK 0ms]
SOX:  injecting features into dialog sox.common.js:63:17
observe: .inbox-dialog sox.common.js:70:13
SOX Access Token: XJUIjR9HFt16u5mikBfSBg)) sox.common.js:46:1
observe: #wmd-redo-button sox.common.js:70:13
observe: [id^="wmd-redo-button"] sox.common.js:70:13
SOX Access Token: XJUIjR9HFt16u5mikBfSBg)) sox.common.js:46:1
Array [  ] sox.features.js:1326:17
GET 
https://rawgit.com/shu8/SE-Answers_scripts/master/dupeClosedMigratedCSS.css [HTTP/2.0 304 Not Modified 679ms]
vwof plugin, exception in ScreenWaveMedia: TypeError: video_data is undefined vwof.js:67:0
GET 
XHR 
https://api.stackexchange.com/2.2/users/364367;630377;167207 [HTTP/1.1 200 OK 33ms]
GET 
XHR 
https://api.stackexchange.com/2.2/questions [HTTP/1.1 400 Bad Request 26ms]
Use of getPreventDefault() is deprecated.  Use defaultPrevented instead. jquery.min.js:3:6598
GET 
https://qa.sockets.stackexchange.com/ [HTTP/1.1 101 Switching Protocols 93ms]
GET 
XHR 
https://l.ghostery.com/api/page/ [HTTP/1.1 204 No Content 57ms]
GET 
XHR 
https://l.ghostery.com/api/census [HTTP/1.1 204 No Content 22ms]
GET 
XHR 
https://l.ghostery.com/api/census [HTTP/1.1 204 No Content 70ms]
GET 
XHR 
https://l.ghostery.com/api/census [HTTP/1.1 204 No Content 70ms]
GET 
XHR 
https://l.ghostery.com/api/census [HTTP/1.1 204 No Content 49ms]
GET 
XHR 
https://l.ghostery.com/api/census [HTTP/1.1 204 No Content 80ms]
GET 
XHR 
https://l.ghostery.com/api/census [HTTP/1.1 204 No Content 86ms]
GET 
XHR 
https://l.ghostery.com/api/census [HTTP/1.1 204 No Content 82ms]
GET 
XHR 
https://l.ghostery.com/api/census [HTTP/1.1 204 No Content 41ms]
GET 
XHR 
https://l.ghostery.com/api/census [HTTP/1.1 204 No Content 63ms]
GET 
XHR 
https://l.ghostery.com/api/census [HTTP/1.1 204 No Content 66ms]
GET 
XHR 
https://l.ghostery.com/api/census [HTTP/1.1 204 No Content 70ms]
GET 
XHR 
https://l.ghostery.com/api/census [HTTP/1.1 204 No Content 77ms]
mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create panel.js:5816:3
Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help http://xhr.spec.whatwg.org/ panel.js:3525:3
not well-formed messages.json:1:1
```

**Comment by fixer1234** [comment]
I just retested again on the example, above, that didn't work and another, and now it's working (v2.0.1a).  I'll close this, again.

**Comment by fixer1234** [comment]
The magic smoke is on a trampoline.  v2.0.1 not working again.

![capture](https://cloud.githubusercontent.com/assets/10065766/19017778/67267464-8815-11e6-8b8e-142c696b1565.PNG)

```
GET 
http://superuser.com/posts/1129727/revisions [HTTP/1.1 200 OK 110ms]
GET 
http://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js [HTTP/1.1 304 Not Modified 86ms]
GET 
http://cdn.sstatic.net/Js/stub.en.js [HTTP/1.1 304 Not Modified 33ms]
GET 
http://cdn.sstatic.net/Sites/superuser/all.css [HTTP/1.1 304 Not Modified 63ms]
GET 
https://www.google-analytics.com/analytics.js [HTTP/2.0 304 Not Modified 163ms]
GET 
http://edge.quantserve.com/quant.js [HTTP/1.1 304 Not Modified 179ms]
GET 
http://b.scorecardresearch.com/beacon.js [HTTP/1.1 200 OK 202ms]
GET 
https://i.stack.imgur.com/DPd3M.jpg [HTTP/1.1 304 Not Modified 73ms]
GET 
https://i.stack.imgur.com/DPd3M.jpg [HTTP/1.1 304 Not Modified 72ms]
GET 
http://i.stack.imgur.com/WTplY.jpg [HTTP/1.1 304 Not Modified 227ms]
GET 
https://i.stack.imgur.com/LkFzd.jpg [HTTP/1.1 304 Not Modified 93ms]
GET 
https://www.gravatar.com/avatar/7028f311d850f69b486756d94d9b57ab [HTTP/2.0 304 Not Modified 70ms]
GET 
http://cdn.sstatic.net/img/share-sprite-new.svg [HTTP/1.1 304 Not Modified 158ms]
GET 
http://cdn.sstatic.net/Sites/superuser/img/sprites.svg [HTTP/1.1 304 Not Modified 158ms]
GET 
http://cdn.sstatic.net/Img/diff-icons/inline-html.png [HTTP/1.1 304 Not Modified 158ms]
GET 
http://cdn.sstatic.net/Img/diff-icons/sidebyside-html.png [HTTP/1.1 304 Not Modified 181ms]
GET 
http://cdn.sstatic.net/Img/diff-icons/sidebyside-markdown.png [HTTP/1.1 304 Not Modified 181ms]
XrayWrapper denied access to property "ready" (reason: value is callable). See https://developer.mozilla.org/en-US/docs/Xray_vision for more information. Note that only the first denied property access from a given global object will be reported.sox.common.js:18
GET 
http://cdn.sstatic.net/Js/full.en.js [HTTP/1.1 304 Not Modified 151ms]
GET 
https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css [HTTP/2.0 304 Not Modified 93ms]
GET 
http://cdn.sstatic.net/Js/revisions.en.js [HTTP/1.1 304 Not Modified 83ms]
SOX:  initializing SOX dialogsox.common.js:63
GET 
http://b.scorecardresearch.com/b [HTTP/1.1 204 No Content 27ms]
SOX:  injecting features into dialogsox.common.js:63
observe: .inbox-dialogsox.common.js:84
SOX Access Token: SETsox.common.js:46
GET 
XHR 
https://api.stackexchange.com/2.2/users/364367;224358;646837 [HTTP/1.1 200 OK 189ms]
GET 
XHR 
https://api.stackexchange.com/2.2/questions [HTTP/1.1 200 OK 173ms]
GET 
https://rawgit.com/shu8/SE-Answers_scripts/master/dupeClosedMigratedCSS.css [HTTP/2.0 304 Not Modified 731ms]
observe: #wmd-redo-buttonsox.common.js:84
observe: [id^="wmd-redo-button"]sox.common.js:84
<unavailable>sox.features.js:1462
<unavailable>sox.features.js:1463
0sox.features.js:1464
GET 
http://qa.sockets.stackexchange.com/ [HTTP/1.1 101 Switching Protocols 83ms]
GET 
http://pixel.quantserve.com/pixel;r=57002735;a=p-c1rF4kxgLUzNc;fpan=0;fpa=P0-1541000686-1462331864564;ns=0;ce=1;cm=;je=1;sr=1600x900x24;enc=n;dst=1;et=1475367887346;tzo=240;ref=http%3A%2F%2Fsuperuser.com%2Fquestions%2F1129727%2Fdrag-down-a-cell-and-get-the-values-that-increment-by-columns;url=http%3A%2F%2Fsuperuser.com%2Fposts%2F1129727%2Frevisions;ogl=type.website%2Cimage.http%3A%2F%2Fcdn%252Esstatic%252Enet%2FSites%2Fsuperuser%2Fimg%2Fapple-touch-icon%402%252Epng%3Fv%3De869e4459439%2Ctitle.Revisions%20to%20Drag%20down%20a%20cell%20and%20get%20the%20values%20that%20increment%20by%20columns%2Cdescription.Q%26A%20for%20computer%20enthusiasts%20and%20power%20users%2Curl.http%3A%2F%2Fsuperuser%252Ecom%2Fposts%2F1129727%2Frevisions [HTTP/1.1 200 OK 460ms]
GET 
https://www.google-analytics.com/collect [HTTP/2.0 200 OK 31ms]
GET 
https://qa.sockets.stackexchange.com/ [HTTP/1.1 101 Switching Protocols 259ms]
```

**Comment by shu8** [comment]
@fixer1234 any luck in the latest v2.0.2dev version? I tweaked it a tiny bit...

**Comment by fixer1234** [comment]
v2.0.2Dev: Opened one within the review queue and it displayed properly.  I retested the link in the previous comment and that still didn't work.  However, I just noticed that that one is actually in the revision history.  You earlier said that the feature isn't currently designed to work there.  So it looks like this feature is working as intended.  I'll close it.

**Comment by fixer1234** [comment]
Spoke too soon.  Just opened an edit in review and got this:

![su title edit](https://cloud.githubusercontent.com/assets/10065766/19422331/ca370560-93e0-11e6-904a-39884c778c8d.png)

```
The connection to wss://qa.sockets.stackexchange.com/ was interrupted while the page was loading. full.en.js:1:6864
GET 
http://superuser.com/review/suggested-edits/583904 [HTTP/1.1 200 OK 51ms]
GET 
http://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js [HTTP/1.1 304 Not Modified 47ms]
GET 
http://cdn.sstatic.net/Js/stub.en.js [HTTP/1.1 304 Not Modified 33ms]
GET 
http://cdn.sstatic.net/Sites/superuser/all.css [HTTP/1.1 304 Not Modified 35ms]
GET 
https://i.stack.imgur.com/DPd3M.jpg [HTTP/1.1 304 Not Modified 74ms]
GET 
https://www.google-analytics.com/analytics.js [HTTP/2.0 304 Not Modified 67ms]
GET 
http://edge.quantserve.com/quant.js [HTTP/1.1 304 Not Modified 42ms]
GET 
http://cdn.sstatic.net/img/share-sprite-new.svg [HTTP/1.1 304 Not Modified 26ms]
GET 
http://cdn.sstatic.net/Sites/superuser/img/sprites.svg [HTTP/1.1 304 Not Modified 19ms]
GET 
http://b.scorecardresearch.com/beacon.js [HTTP/1.1 200 OK 21ms]
GET 
http://b.scorecardresearch.com/b [HTTP/1.1 204 No Content 20ms]
GET 
http://cdn.sstatic.net/Js/full.en.js [HTTP/1.1 304 Not Modified 18ms]
XrayWrapper denied access to property "ready" (reason: value is callable). See https://developer.mozilla.org/en-US/docs/Xray_vision for more information. Note that only the first denied property access from a given global object will be reported. sox.common.js:18:0
GET 
https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css [HTTP/2.0 304 Not Modified 116ms]
SOX:  initializing SOX dialog sox.common.js:63:17
GET 
http://pixel.quantserve.com/pixel;r=413005515;a=p-c1rF4kxgLUzNc;fpan=0;fpa=P0-2087723673-1465952398859;ns=0;ce=1;cm=;je=1;sr=2048x1152x24;enc=n;dst=1;et=1476664889537;tzo=240;ref=http%3A%2F%2Fsuperuser.com%2Freview;url=http%3A%2F%2Fsuperuser.com%2Freview%2Fsuggested-edits%2F583904;ogl=type.website%2Cimage.http%3A%2F%2Fcdn%252Esstatic%252Enet%2FSites%2Fsuperuser%2Fimg%2Fapple-touch-icon%402%252Epng%3Fv%3De869e4459439%2Ctitle.Review%20Suggested%20Edits%2Cdescription.Q%26A%20for%20computer%20enthusiasts%20and%20power%20users%2Curl.http%3A%2F%2Fsuperuser%252Ecom%2Freview%2Fsuggested-edits%2F583904 [HTTP/1.1 200 OK 85ms]
GET 
https://www.google-analytics.com/collect [HTTP/2.0 200 OK 23ms]
SOX:  injecting features into dialog sox.common.js:63:17
observe: .inbox-dialog sox.common.js:84:13
SOX Access Token: SET sox.common.js:46:1
observe: .review-more-instructions ul sox.common.js:84:13
observe: #wmd-redo-button sox.common.js:84:13
observe: [id^="wmd-redo-button"] sox.common.js:84:13
observe: .review-status sox.common.js:84:13
GET 
http://cdn.sstatic.net/Js/review.en.js [HTTP/1.1 304 Not Modified 19ms]
GET 
https://rawgit.com/shu8/SE-Answers_scripts/master/dupeClosedMigratedCSS.css [HTTP/2.0 304 Not Modified 607ms]
vwof plugin, exception in ScreenWaveMedia: TypeError: video_data is undefined vwof.js:67:0
GET 
XHR 
https://api.stackexchange.com/2.2/users/ [HTTP/1.1 200 OK 54ms]
GET 
XHR 
https://api.stackexchange.com/2.2/questions [HTTP/1.1 400 Bad Request 123ms]
GET 
https://qa.sockets.stackexchange.com/ [HTTP/1.1 101 Switching Protocols 115ms]
GET 
http://superuser.com/content/img/progress-dots.gif [HTTP/1.1 304 Not Modified 233ms]
POST 
XHR 
http://superuser.com/review/next-task/583904 [HTTP/1.1 200 OK 49ms]
fire: .review-status sox.common.js:91:29
GET 
http://cdn.sstatic.net/Img/diff-icons/sidebyside-html.png [HTTP/1.1 304 Not Modified 98ms]
GET 
http://cdn.sstatic.net/Img/diff-icons/sidebyside-markdown.png [HTTP/1.1 304 Not Modified 98ms]
TypeError: $editor.text(...).match(...) is null sox.features.js:1714:38
GET 
https://i.stack.imgur.com/J5ozr.png [HTTP/1.1 304 Not Modified 28ms]
GET 
https://www.gravatar.com/avatar/a007be5a61f6aa8f3e85ae2fc18dd66e [HTTP/2.0 304 Not Modified 18ms]
GET 
XHR 
https://l.ghostery.com/api/page/ [HTTP/1.1 204 No Content 136ms]
GET 
XHR 
https://l.ghostery.com/api/census [HTTP/1.1 204 No Content 114ms]
GET 
XHR 
https://l.ghostery.com/api/census [HTTP/1.1 204 No Content 110ms]
GET 
XHR 
https://l.ghostery.com/api/census [HTTP/1.1 204 No Content 123ms]
GET 
XHR 
https://l.ghostery.com/api/census [HTTP/1.1 204 No Content 116ms]
GET 
XHR 
https://l.ghostery.com/api/census [HTTP/1.1 204 No Content 118ms]
GET 
XHR 
https://l.ghostery.com/api/census [HTTP/1.1 204 No Content 127ms]
GET 
XHR 
https://l.ghostery.com/api/census [HTTP/1.1 204 No Content 131ms]
GET 
XHR 
https://l.ghostery.com/api/census [HTTP/1.1 204 No Content 138ms]
GET 
XHR 
https://l.ghostery.com/api/census [HTTP/1.1 204 No Content 143ms]
GET 
XHR 
https://l.ghostery.com/api/census [HTTP/1.1 204 No Content 145ms]
mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create panel.js:5816:3
Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help http://xhr.spec.whatwg.org/ panel.js:3525:3
not well-formed messages.json:1:1
```

However, when I reloaded the page to capture the console output, the edit appeared correctly.  So it looks like another case where page reloads are needed for the feature to work (see also the comment scores).

**Comment by shu8** [comment]
thanks, I'll see if I can find anything... :/

**Comment by shu8** [comment]
@fixer1234 hmmm when it *doesn't* work, can you remember if it's always after you click 'next' in review? I think that *might* be the problem here... because it always works when I directly go on a link, but maybe if as you're going through a review it doesn't work...?

Does that sound like what could have been happening to you?

**Comment by fixer1234** [comment]
@shu8 Using what may be the previous DEV version.  I went into the Edit Review history and picked three recent questions that contained a title edit.  Going directly to the page displayed the title edits as intended.  I'll look for examples in the queue that I get to with "Next" and see what happens.

**Comment by shu8** [comment]
@fixer1234 I think I might have fixed this in the latest dev version b, but please do keep a look out for suggested edits in the review queue! :)

**Comment by fixer1234** [comment]
@shu8 The token is messed up in this version.  Clicking the cog in SO doesn't trigger the get token action, so there's an endless triggering of prompts and SO tabs on every page.

**Comment by shu8** [comment]
@fixer1234 just pushed a fix to dev...

**Comment by shu8** [comment]
The problem basically seems to be that the Mutation Observer (the thing that checks for when to run the feature) is currently checking for an element that only appears on *completed* reviews! So I just need to find a suggested edit in a queue and inspect element on it and find an element that will always exist! I'll get this fixed as soon as I see a suggested edit anywhere!!! :)

**Comment by shu8** [comment]
@fixer1234 this *might* have been fixed in this version; I guessed an element that should exist in pending suggested edits, so please keep looking out for title edits [in latest dev version g](https://github.com/soscripted/sox/raw/dev/sox.user.js) :)

**Comment by fixer1234** [comment]
@shu8 Installed Dev G.  Just came across a single proposed edit in the Edit Review queue and it had a title edit.  On my system, only the modified word was colored in-place, so it looks like the guess didn't fix it.  If you want to compare output on your own system, it's: http://superuser.com/review/suggested-edits/589717

![su edit title](https://cloud.githubusercontent.com/assets/10065766/19913969/67ced1a6-a07d-11e6-848b-5c5376c8e5bf.png)

**Comment by fixer1234** [comment]
@shu8 Another case of an apparent moving target.  My previous comment was with ver G, which I'm still using.  I'm virtually sure that this issue was still behaving the same way yesterday.  I just clicked on the example link from the last comment and it now displays correctly.  

I'll close this issue, but I think some SE programmers are messing with you.

**Comment by shu8** [comment]
@fixer1234 yeah, I thought the problem was only if you were going on to a next review item in the review queue...?

**Comment by fixer1234** [comment]
@shu8 No, I was getting it on ones not accessed via Next.  But I haven't tested that case.  If I come across one in the review queue, I'll try to remember to check.

**Comment by fixer1234** [comment]
@shu8 OK, just came across an edit review with a title edit, a single review post (no next).  This is Dev P and the feature isn't working.  The posts is: http://superuser.com/review/suggested-edits/591825, and it looks like this:

![su title edit](https://cloud.githubusercontent.com/assets/10065766/20081637/e77fdb02-a51e-11e6-9839-8c755099e6dd.png)

**Comment by shu8** [comment]
I've added the help wanted tag to this, because I can't find the solution to it :(

To anyone who might be able to help:

The issue is (I think...) that the mutationobserver isn't looking at the right element to detect new reviews after clicking next/skip. We need to experiment with different element IDs/classes to see one that changes every time.

**Comment by IStoleThePies** [comment]
@shu8 I'll try and check it out once a suggested edit pops up. On a side note I noticed that "Make title edits show seperately rather than merged in edit suggestions" misspells "separately".

**Comment by shu8** [comment]
@IStoleThePies thanks! I hope you find a solution! :P 

Nice catch! I've fixed the typo locally

**Comment by fixer1234** [comment]
@shu8 I'm now running Dev K and have seen a bunch of title edits in the review queue.  So far, I think all of them are displaying correctly.  I'll keep my eye out for this, but through the prior dev version on which I saw title edits, they were still not displayed correctly.  Could be something else you fixed solved this problem.  At least a hopeful sign.

**Comment by shu8** [comment]
@fixer1234 hmmm it looks like the change I made to the MutationObserver helper that broke all those features you've reported actually fixed this one! 😃 

I'm going to close this, and hope for it never to be reopened again 😝 

cc/ @IStoleThePies it's working!!!
